### ISSUE TITLE
Duplication of data set is prohibitively slow with large data

### ISSUE THREAD

**Issue by kadamwhite** [vega/compass#120]
When generating encodings, the dataset is duplicated repeatedly within the `genEncodingsFromEncs` method: [see `encodings.js`](https://github.com/vega/compass/blob/dc0b9220346fb5d5c9f3f60b9b520e5509de43d2/src/gen/encodings.js#L27-L43). The `vl.duplicate` method works by serializing and deserializing the input as JSON, which is computationally expensive. As an example with a dataset of 1000 rows each call to `genEncodingsFromEncs` takes 50 milliseconds, adding up to over a second of processing required to complete the calling `genClusters` method:

![image](https://cloud.githubusercontent.com/assets/442115/10464980/89b9c19c-71ba-11e5-8afb-e80dea24d14b.png)

Removing this duplication drops the runtime of `genEncodingFromFields` down to 14ms, so `genClusters` completes in 53% of the time it did when using the duplication:

![image](https://cloud.githubusercontent.com/assets/442115/10465068/f9af714a-71ba-11e5-9290-a361c28fecb2.png)

To my untrained eyes, the functionality of Voyager *appeared* to be unimpacted by the removal of the serialization/deserialization; I am unfamiliar with the reason why this expensive duplication is necessary, so I am flag this for @kanitw to review in the future.

If there's a way to improve the efficiency of this initial encoding generation, or even to move the generation to on-demand code, it would significantly improve Voyager's performance when loading small-to-mid-size datasets (~1000 rows).

**Comment by kadamwhite** [comment]
Here's the diff of the change I made to yield the above profile:
```diff
diff --git a/src/gen/encodings.js b/src/gen/encodings.js
index 1c90268..24bea6f 100644
--- a/src/gen/encodings.js
+++ b/src/gen/encodings.js
@@ -27,12 +27,12 @@ function genEncodingsFromFields(output, fields, stats, opt, nested) {
 function genEncodingsFromEncs(output, enc, stats, opt) {
   getMarktypes(enc, stats, opt)
     .forEach(function(markType) {
-      var e = vl.duplicate({
+      var e = {
           data: opt.data,
           marktype: markType,
           encoding: enc,
           config: opt.config
-        }),
+        },
         encoding = finalTouch(e, stats, opt),
         score = rank.encoding(encoding, stats, opt);
 
@@ -61,4 +61,4 @@ function finalTouch(encoding, stats, opt) {
     }
   });
   return encoding;
-}
\ No newline at end of file
+}

```

**Comment by kanitw** [comment]
This method was implemented before inline data is supported.  
Data should not definitely be cloned.  I will fix this sometimes this week.
