### ISSUE TITLE
How to run and check the demo?

### ISSUE THREAD

**Issue by praveensastry** [vega/compass#137]
Hi,
I had cloned the repo but it is very unclear how one(probably only to me) can use this library and get visualization recommendation for a given dataset. Can you please help me out here?

**Comment by kanitw** [comment]
Apologies!  The demo is actually outdated and will be removed soon.  

We're working on cleaning up the API and updating the docs.  But currently we're focusing on vega-lite.
So for now, please take a look at how Voyager is using Compass.  

Take a look at https://github.com/vega/voyager/blob/master/src/app/visrec/visrec.service.js and track all `cp.xxx` calls.
