### ISSUE TITLE
Odd recommendations

### ISSUE THREAD

**Issue by domoritz** [vega/compass#140]
This is currently happening in voyager. Somehow it recommends col without bin and a size encodings with overlap. 

<img width="1339" alt="screen shot 2015-12-04 at 20 02 12" src="https://cloud.githubusercontent.com/assets/589034/11605922/fead3576-9ac1-11e5-8c19-0225866f1319.png">

**Comment by kanitw** [comment]
The overlap is vega-lite’s bug and it is fixed.   The weird color is a bug in vega-lite-ui and it is fixed. 

Please re-open if you have any other specific “weird” cases.

**Comment by domoritz** [comment]
Certainly https://github.com/vega/compass/issues/142 is very odd
