### ISSUE TITLE
Prevent using bar with log scale

### ISSUE THREAD

**Issue by kanitw** [vega/compass#153]
@yhoonkim  Looks like we sometimes recommending using log scale with bar, which is a bad practice.

For Compass, we definitely should have this option.   
For your user study, you might want to consider if you want to exclude bar with log scale.

**Comment by yhoonkim** [comment]
Hmm... Can I ask why bar with log scale is bad?
![image](https://cloud.githubusercontent.com/assets/6269456/12863980/1bae26dc-cc34-11e5-84e0-9d9dafbbeb0a.png)

**Comment by kanitw** [comment]
http://www.graphpad.com/support/faqid/1477/

**Comment by yhoonkim** [comment]
Oh, I got it! Thanks~! :)
