### ISSUE TITLE
Don't include 0

### ISSUE THREAD

**Issue by domoritz** [vega/compass#69]
This chart would be super interesting but is pretty much useless

![screen shot 2015-03-01 at 21 18 36](https://cloud.githubusercontent.com/assets/589034/6435721/93b8d8cc-c058-11e4-8f95-b40d1b3f9f42.png)

**Comment by kanitw** [comment]
Looking at this code, I feel like we're solving the problem at the wrong part.  It's just the year that's problematic.   @domoritz

**Comment by domoritz** [comment]
Yeah, in this case. But I agree until we have another use case.
